x = input("Enter first number:")
y = input("Enter second number:")
a = int(x)
b = int(y)
print("sum :", a+b)
print("mul :", a*b)
print("sub :", a-b)
print("div :",a/b)
print("rou_div:", a//b)
print("pow :", a**b)